### ISSUE TITLE
Select form didn't show all the options after submiting the form with form validation error triggered

### ISSUE THREAD

**Issue by rifandaadam** [ahmetdogukankonuk/codeigniter-3-cms#1]

**Comment by ahmetdogukankonuk** [comment]
Hello Adam, could you send me a screenshot via mail (ahmetdogukankonuk@gmail.com) i don't understand the problem.

**Comment by rifandaadam** [comment]
sure, beside this attachment i've also send you screenrecord via email 
https://user-images.githubusercontent.com/47600046/200710837-8af90aba-b546-4887-8b82-f3a357db7c5b.mp4

**Comment by ahmetdogukankonuk** [comment]
Hi Adam, i will fix the problem, the select form will show all options after form validation error triggered. It is possible that you get form validation error because the base url config is wrong. Did you change the base_url as "$config['base_url'] = 'http://10.10.52.14/test/panel/';" ?

**Comment by rifandaadam** [comment]
> Hi Adam, i will fix the problem, the select form will show all options after form validation error triggered. It is possible that you get form validation error because the base url config is wrong. Did you change the base_url as "$config['base_url'] = 'http://10.10.52.14/test/panel/';" ?

yes i've changed the base url to 10.10.52.14/test/panel/

**Comment by ahmetdogukankonuk** [comment]
I just fixed the problem, now you are able to see all the options after getting validation error. Please check the last commit. And for the validation error; database name, routes, function name or the names of inputs might be changed.

**Comment by rifandaadam** [comment]
thank you, yes, it fixed the problem 👍

**Comment by ahmetdogukankonuk** [comment]
You are welcome Adam! :)
